name: Test MultiTool Action

on:
  push:
    branches-ignore:
      - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test MultiTool Action
        uses: wack/multitool-action@${{ github.sha }}
        with:
          input-string: "test input"